name: Deploy WordPress Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies (Sass)
      run: npm install -g sass

    # - name: Compile SCSS to CSS
    #   run: |
    #     sass --no-source-map --style=compressed scss/style.scss:css/style.css

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: Upload WordPress theme to server
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -f "
        open $FTP_HOST
        user $FTP_USERNAME $FTP_PASSWORD
        mirror -R --delete --verbose \
        --exclude \".git*\" \
        --exclude \".github*\" \
        ./ /dev.jan-mazan.develoart.pl/wordpress82323/wp-content/themes/jan_mazan
        bye
        "
