name: Deploy WordPress Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: Upload WordPress theme to server
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -f "
        open $FTP_HOST
        user $FTP_USERNAME $FTP_PASSWORD
        mirror -R --delete --verbose ./ /public_html/autoinstalator/dev.jan-mazan.develoart.pl/wordpress82323/wp-content/themes/jan-mazan
        bye
        "
